### ISSUE TITLE
Upgrade to Typescript 1.5.3 (none beta) release

### ISSUE THREAD

**Issue by bd82** [sebastian-lenz/typedoc#122]
[Typescript 1.5.3](https://www.npmjs.com/package/typescript) has been released.

TypeDoc is currently using: 1.5.0-beta
I've tried upgrading it myself hoping it was just a simple version change.
However the tests fail and all the generated specs.json become nearly empty...

Thanks.
Shahar.

**Comment by sebastian-lenz** [comment]
No, it's not possible to simply change the dependency, mainly because of the constant enumerations the TypeScript compiler uses. You can only use the version of TypeScript with TypeDoc it has been compiled and published with.

But thank you for the notice of the new release version. I've published a new version of TypeDoc compiled against the latest TypeScript release.

**Comment by bd82** [comment]
I saw the change and now understand you had to update tsc.d.ts 
because enums in typescript are in-lined using their compile time value.

Thanks for the quick response and for TypeDocs :)
