### ISSUE TITLE
EventEmitter events

### ISSUE THREAD

**Issue by rogierschouten** [sebastian-lenz/typedoc#17]
Hi Sebastian,

You really filled a void with this tool, thank you! I'm currently deriving a class from EventEmitter, and I was searching for a way to document the events being emitted. Would it be an idea to introduce an extra @event tag?  I'd be happy to try and implement this if you could give me some pointers as to how to do so.

Rogier

**Comment by jesperstarkar** [comment]
What is the syntax you ended up with here?

**Comment by aciccarello** [comment]
I think this was implemented as just marking symbols as an event type. The test example is just a static string property.

```TypeScript
class EventDispatcher
{
    /**
     * This is an event documentation.
     * @event
     */
    static EVENT_CLICK:string = 'click';

}
```

**Comment by cancerberoSgx** [comment]
I've written some alternatives to describe/document events in TypeDoc here : https://cancerberosgx.github.io/javascript-documentation-examples/examples/typedoc-tutorial-basic/docs/docco/src/index.html#events

Personally I don't like the static properties approach, it force me to declare extra properties, and it doesn't allow me to declare events at the interface level. Also it has the same problems at the proposed by @rogierschouten  (event names appear stacked under a method name) and it makes it hard to see and 
 maintain the relationship between event name and corresponding listener signature. 

In that document I analyze this two proposals and I propose a third one that IMO present events optimally, Basically is declaring the listener signature type outside the interface and name it like the event. (so it encapsulate the relationship event name-listener signature). Tag it with @event and in the overrides of method on() emit() etc use it to reference the listener signature. Then the hack is instructing the plugin to move the type as a @event member of the interface. Well, conceptually I don't know if it is a hack or not since the concept of events doesn't exist in JavaScript/TypeScript. The plugin is called "as-member-of" and jsdoc3 has some similar tags like @member or @lends  so not sure if it's too bad. 

If you could review that material and give me your opinion I would very appreciate it. Hope it could help at least  as a starting point for a discussion :)

Thanks.

**Comment by cancerberoSgx** [comment]
So we agree that what .d.ts authors are doing overloading addListener(), on(), etc for strict handler typechecking is the way to go for declaring / documenting events, right ? 

Do you think TypeDoc should do "magic" and treat EventEmitter methods in a special way to automatically generate event members ?  Do you think that users shouldn't use @event but the tool automatically create these event members? 

If so, I like the idea, as long as this magic is done by a plugin and not typedoc core.  Will try to prototype something when I have time. Thanks
