### ISSUE TITLE
Documentation Generation and AMD modules

### ISSUE THREAD

**Issue by Mudhoax** [sebastian-lenz/typedoc#45]
Will this project eventually support documentation generation for RequireJS projects?

Currently this appears to be getting extremely confused at resolving modules when using the --module amd flag.

I've knocked up a quick example using requireJS.
![requirejs](https://cloud.githubusercontent.com/assets/1621099/5229926/5ae3a846-7716-11e4-9b10-438ff5364fae.png)

and another using commonJS.
![commonjs](https://cloud.githubusercontent.com/assets/1621099/5229928/62361f7a-7716-11e4-8ca4-8b0976a51673.png)

I would have expected the output to have been the same between the two projects.

I can upload the source of both if required.

Regards,
Ian Munro

**Comment by sebastian-lenz** [comment]
Hi Mudhoax, nice to hear from you. Actually this difference reflects the way the compiler works when the module mode is set to AMD.

This will greatly change with TypeScript 1.1/1.3 support. The new compiler no longer changed the internal data structures due to the selected module mode. So with the upcoming release of TypeDoc 0.2 you can decide in which way you want your code to be documented independently of the selected module mode through the <code>--mode</code> command line argument.
