### ISSUE TITLE
Generic parameters are not visible in function parameters / returns

### ISSUE THREAD

**Issue by paztis** [sebastian-lenz/typedoc#55]
example:

code: 
function ajax<_R_>(pUrl: string): Promise<_R_> {
    ....
}

generated doc: 
ajax<_R_>(pUrl: string): Promise => no reference of the generic parameter in response

code:
class Test<_Data_>
{
    testFunction(array: Array<_Data_>): Array<_Data_> {
        ...
    }
}

generated doc: 
Class Test<_Data_> => ok it's good
testFunction(array: Array): Array => no reference of the _Data_ generic parameter

**Comment by sebastian-lenz** [comment]
Hi paztis, thank you for sharing this. It's not a real bug, the type reflection is currently not aware of type parameters. I'll check into this one.

**Comment by paztis** [comment]
Thanks

**Comment by sebastian-lenz** [comment]
Changes are in the repository, will be available with TypeDoc 0.2.3

**Comment by upta** [comment]
Hey Sebastian,

I'm running into this same issue in the json file (this time I double checked and I have the npm 0.2.3 version ;)  When I generate the whole docs instead of just the json file, the type params show up correctly.

Let me know if you need me to send you samples of what I'm seeing, thanks!
